/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SesameApp;

import AccesGUI.*;
import HomeGUI.*;
import LinkingGUI.*;
import SharingGUI.*;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author LamineBA
 */
public class CreateAccesKey implements java.io.Serializable{
    
    private final ArrayList<String> key_list;
    private final int number_key;
    
    public CreateAccesKey (int nbre_key){
        number_key = nbre_key;
        System.out.println("Creation des clés d'accès");
        key_list = new ArrayList<>(number_key);
        String [] key_temp = makeKey(number_key);
        for (int i=0; i<key_temp.length; i++){
            key_list.add(key_temp[i]);
            //System.out.println("KeyList["+i+"] = " + key_list.get(i));
        }
        System.out.println("Key size = " + key_list.size());
    }
    
    /**
     * Methode : makeKey allow you to create all the key for one SESAME
     * @param number_of_key
     * @return 
     */
    private static String[] makeKey( int number_of_key){
       //System.out.println("Methode makeKey()");
       String [] key_generated = new String[number_of_key];
       int count=0;
       String key = "";
       char [] char_table_upper = {'A','Z','E','R','T','Y','U','I','O','P',
                                   'Q','S','D','F','G','H','J','K','L','M',
                                          'W','X','C','V','B','N'};
       
       char [] char_table_lower = {'a','z','e','r','t','y','u','i','o','p',
                                   'q','s','d','f','g','h','j','k','l','m',
                                          'w','x','c','v','b','n'};
       
       char [] char_table_number = {'0','2','4','6','8','1','3','5','7','9'};
       
       int random_char_upper = 0;
       int random_char_lower = 0;
       int random_number     = 0;
       
       String s_char_upper          = "";
       String s_char_lower          = "";
       String s_char_number         = "";
       String s_random_char_upper   = "";
       String s_random_char_lower   = "";
       String s_random_number       = "";
       
       Random rand = new Random();

       while (count < number_of_key){
           while (key.length()<99){ //126 = 9*14
                // Generate the random integer
                random_char_upper = rand.nextInt(char_table_upper.length - 1);
                random_char_lower = rand.nextInt(char_table_lower.length - 1);
                random_number = rand.nextInt(char_table_number.length -1);

                // Get the char corresponding on the generated random
                s_char_upper  = String.valueOf(char_table_upper[random_char_upper]);
                s_char_lower  = String.valueOf(char_table_lower[random_char_lower]);
                s_char_number = String.valueOf(char_table_number[random_number]);

                //Format the random number to %2d => 2 = 02
                s_random_char_upper = String.format("%02d", random_char_upper);
                s_random_char_lower = String.format("%02d", random_char_lower);
                s_random_number     = String.format("%02d", random_number);

                // Make the key in the correct form
                key+= s_random_char_upper + s_char_upper;
                key+= s_random_char_lower + s_char_lower; 
                key+= s_random_number     + s_char_number;
            }
           
           // Now add key on the String array
           key_generated[count] = key;
           //System.out.println("Key[" + count + "] = " + key_generated[count]);
           key = "";
           count ++;
       }
       
       return key_generated;
    }
    
    
    /**
     * Methode : getOneValideKey () allow you to get one valide key which is generated
     * @return key which is generated by the class
     */
    public String getOneValideKey(){
        String key = "";
        
        Random rand = new Random(); 
        int key_index = rand.nextInt(key_list.size() -1);
        System.out.println("Size of the arraylist before = " + key_list.size());
        key = key_list.get(key_index);
        key_list.remove(key_index);
        System.out.println("Index of gotten key = " + key_index + " Key = " + key);
        return key;
    }
    
    @Override
    public String toString(){
        String chaine = "\n"+ "<---------------------------------------------------->" + "\n"+
                              "<--- ALL GENERATED KEY FOR THIS SESAME DEVICE     --->" + "\n"; 
        for (int i=0; i<key_list.size(); i++){
            chaine += " KEY["+i+"] = " + key_list.get(i) + "\n";
        }                
        chaine += "<---------------------------------------------------->" + "\n";
        return chaine;
    }
    
    private static final long serialVersionUID = 42L; 

    public static void main (String [] args){
        CreateAccesKey key = new CreateAccesKey(10);
        String temp = key.getOneValideKey();
    }
    
}
