/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LinkingGUI;

import AccesGUI.*;
import HomeGUI.*;
import SesameApp.*;
import SharingGUI.*;

import com.pi4j.io.serial.SerialPortException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LamineBA
 */
public class PeripheriqueSummaryInformation extends javax.swing.JFrame implements ConstantsConfiguration{

    private PeripheriqueInformation periph;
    private SerialPortGPIO port;
    
    public PeripheriqueSummaryInformation() {
        initComponents();
        
        /* Deserializable of the file containing the information 
           of the periph to add the indentifier number and password */          
        periph = null;
        File file = new File("peripherique_information.ser");
        try (FileInputStream fileIn = new FileInputStream(file); ObjectInputStream in = new ObjectInputStream(fileIn)) {
            periph = (PeripheriqueInformation) in.readObject();
            System.out.println("Deserialization complete");
            System.out.println("Debut écriture");
            type_bien_jlabel.setText(periph.getTypeBien());
            type_appartenance_jlabel.setText(periph.getTypeAppartenance());
            emplacement_jlabel.setText(periph.getEmplacement());
            type_porte_jlabel.setText(periph.getTypePorte());
            commentaire_jTextField.setText(periph.getCommentaire());
            numero_nom_voie_jlabel.setText(periph.getNumeroRue() + " " + periph.getNomRue());
            code_postale_ville_jlabel.setText(periph.getCodePostale() + " " + periph.getVille());
            pays_jlabel.setText(periph.getPays()); 
            System.out.println("Fin écriture");
        }catch(IOException i)
        {
            System.out.println("Return");
        }catch(ClassNotFoundException c)
        {
           System.out.println("PeripheriqueInformation class not found");
        }
        
        try {
            // open the default serial port provided on the GPIO header
            int baudrate = 115200;
            port = new SerialPortGPIO(baudrate);
        }
        catch(SerialPortException ex) {
            System.out.println(" ==>> SERIAL SETUP FAILED : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        type_appartenance_jlabel = new javax.swing.JLabel();
        numero_nom_voie_jlabel = new javax.swing.JLabel();
        emplacement_jlabel = new javax.swing.JLabel();
        type_porte_jlabel = new javax.swing.JLabel();
        code_postale_ville_jlabel = new javax.swing.JLabel();
        pays_jlabel = new javax.swing.JLabel();
        commentaire_jTextField = new javax.swing.JTextField();
        type_bien_jlabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lancer_procedure = new javax.swing.JToggleButton();
        corriger_info = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recapitulatif des informations du periphérique");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Recapitulatif des informations du periphérique");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Type de Bien : ");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setText("Type d'appartenance : ");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setText("Emplacement : ");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setText("Type de porte : ");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setText("Commentaire sur le periphérique : ");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("Adresse de Résidence ");

        type_appartenance_jlabel.setBackground(new java.awt.Color(204, 255, 204));
        type_appartenance_jlabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        type_appartenance_jlabel.setText("type appartenance");

        numero_nom_voie_jlabel.setBackground(new java.awt.Color(204, 255, 204));
        numero_nom_voie_jlabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        numero_nom_voie_jlabel.setText("numero et nom de la voie");

        emplacement_jlabel.setBackground(new java.awt.Color(204, 255, 204));
        emplacement_jlabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        emplacement_jlabel.setText("emplacement");

        type_porte_jlabel.setBackground(new java.awt.Color(204, 255, 204));
        type_porte_jlabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        type_porte_jlabel.setText("type de porte");

        code_postale_ville_jlabel.setBackground(new java.awt.Color(204, 255, 204));
        code_postale_ville_jlabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        code_postale_ville_jlabel.setText("code postale et ville");

        pays_jlabel.setBackground(new java.awt.Color(204, 255, 204));
        pays_jlabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        pays_jlabel.setText("pays");

        commentaire_jTextField.setBackground(new java.awt.Color(204, 255, 204));
        commentaire_jTextField.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        commentaire_jTextField.setText("Porte de ma résidence principale");

        type_bien_jlabel.setBackground(new java.awt.Color(204, 255, 204));
        type_bien_jlabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        type_bien_jlabel.setText("type de bien");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(type_appartenance_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(62, 62, 62)
                                .addComponent(type_bien_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(commentaire_jTextField)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type_porte_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emplacement_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero_nom_voie_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(code_postale_ville_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pays_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(type_bien_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_appartenance_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(emplacement_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_porte_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commentaire_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numero_nom_voie_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(code_postale_ville_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pays_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {code_postale_ville_jlabel, emplacement_jlabel, numero_nom_voie_jlabel, pays_jlabel, type_appartenance_jlabel, type_porte_jlabel});

        jPanel3.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        lancer_procedure.setBackground(new java.awt.Color(153, 255, 153));
        lancer_procedure.setText("Lancer la Procedure");
        lancer_procedure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lancer_procedureMouseReleased(evt);
            }
        });

        corriger_info.setBackground(new java.awt.Color(255, 153, 153));
        corriger_info.setText("Corriger les infos");
        corriger_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                corriger_infoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(corriger_info)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lancer_procedure)
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corriger_info, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lancer_procedure, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        setSize(new java.awt.Dimension(409, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lancer_procedureMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lancer_procedureMouseReleased
        // 1. Instanciation de la communication uart
        // 2. Envoie de la trame demande de rattachement d'un Sesame; Periphérique verifie s'il est rattaché ou pas
        // 3. Peripherique renvoie une autorisation de rattachement
        // 4. Sesame envoie le fichier d'information du peripherique et son identifiant
        
        // Diseable the acces to the acces
        lancer_procedure.setEnabled(false);
        corriger_info.setEnabled(false);
        
        boolean status_linking_sesame = false;
        boolean status_linking_owner = false;
        boolean flag = true;
        int tempo = 0;
        // SEND "BONJOUR" and wait the answer of the device. The expected answer is "BONJOUR"  
        try {
            flag = true;
            tempo = 0;
            port.sendData(BONJOUR);
        }catch(InterruptedException e){
            flag = false;
            System.out.println("Impossible to the send the following message : BONJOUR");
        }
        
        // Check the answer of the device in the while loop
        while (flag){
            if (tempo>1000){
                flag=false;
                System.out.println("Tempo d'attente de la réponse du périphérique a expiré");
                tempo = 0;
            }
            else{
                flag = (port.getLastReceivedData()!=null && !port.getLastReceivedData().equals(BONJOUR));
                if (!flag){
                    System.out.println("|BONJOUR| sur PeripheriqueSummaryInformation");
                }
                tempo = tempo + 100;
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {}
            }
        }

        // Wait 10 secondes
        tempo = 0;
        int seconde = 1000;
        while (tempo<5*seconde){
            tempo = tempo + seconde;
            try {
                Thread.sleep(seconde);
            } catch (InterruptedException ex) {}
        }
        
        // The expected answer is received by the SESAME 
        if (!flag){
            try {
                flag = true;
                tempo = 0;
                port.sendData(DEMANDE_ENREGISTREMENT_PROPRIETAIRE);
                System.out.println( DEMANDE_ENREGISTREMENT_PROPRIETAIRE + " : envoyé avec succes");
            }catch(InterruptedException e){
                flag = false;
                System.out.println("Impossible to the send the following message : " + DEMANDE_ENREGISTREMENT_PROPRIETAIRE);
            }
        }
        
        while (flag){
            if (tempo>1000){
                flag=false;
                System.out.println("Tempo d'attente de la réponse du périphérique a expiré");
                tempo = 0;
            }
            else{
                flag = (port.getLastReceivedData()!=null && !port.getLastReceivedData().equals(ENREGISTREMENT_PROPRIETAIRE_AUTORISEE));
                
                if (!flag){
                    System.out.println("|ENREGISTREMENT_PROPRIETAIRE_AUTORISEE| recu de la part du périphérique");
                }
                tempo = tempo + 100;
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {}
            }
        }

        // Wait 10 secondes
        tempo = 0;
        seconde = 1000;
        while (tempo<5*seconde){
            
            System.out.println("Tempo end = " + tempo);
            tempo = tempo + seconde;
            try {
                Thread.sleep(seconde);
            } catch (InterruptedException ex) {}
        }
        
        // The expected answer is received by the SESAME 
        if (!flag){
            System.out.println("Enregistrement du proprietaire autorisé par le periphérique");
            String [] data_to_send = arrangeOwnerInformationForLinking();
            flag = true;
            tempo = 0;
            try {
                // Arrange the owner information and Send it
                port.sendData(data_to_send);
            } catch (InterruptedException ex) {}
        }
        
        
        //boolean status_linking_owner = false;
        while (flag){
            if (tempo>7000){
                flag=false;
                System.out.println("Tempo d'attente de la réponse du périphérique a expiré");
                tempo = 0;
            }
            else{
                flag = (port.getLastReceivedData()!=null && !port.getLastReceivedData().equals(PROPRITAIRE_ENREGISTREE_CORRECTEMENT));
                if (!flag){
                    System.out.println("|PROPRITAIRE_ENREGISTREE_CORRECTEMENT| dans le périphérique");
                    status_linking_owner = true;
                }
                else{
                    tempo =  tempo + 100;
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {}
                }
            }
        }
        
        // Wait 10 secondes
        tempo = 0;
        seconde = 1000;
        while (tempo<5*seconde){
            
            System.out.println("Tempo = " + tempo);
            tempo = tempo + seconde;
            try {
                Thread.sleep(seconde);
            } catch (InterruptedException ex) {}
        }
        
        // Send Data about the connection between Device and Sesame
        try {
            flag = true;
            tempo = 0;
            System.out.println("BONJOUR : envoyé avec succes");
            port.sendData(BONJOUR);
        }catch(InterruptedException e){
            System.out.println("Impossible to the send the following message : BONJOUR");
        }
        
        // Check the answer of the device in the while loop
        while (flag){
            if (tempo>1000){
                flag=false;
                System.out.println("Tempo d'attente de la réponse du périphérique a expiré");
                tempo = 0;
            }
            else{
                flag = (port.getLastReceivedData()!=null && !port.getLastReceivedData().equals(BONJOUR));
                if (!flag){
                    System.out.println("|BONJOUR| recu de la part du périphérique");
                }
                
                tempo = tempo + 100;
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {}
            }
        }
        
        // The expected answer is received by the SESAME 
        if (!flag){
            // Send DEMANDE_RATTACHEMENT to the device and wait for the answer
            try {
                flag = true;
                tempo = 0;
                port.sendData(DEMANDE_RATTACHEMENT_SESAME);
            }catch(InterruptedException e){
                flag = false;
                System.out.println("Impossible to the send the following message : DEMANDE_RATTACHEMENT_SESAME : " + e.getMessage());
            }
        }
        
        // Check the answer of the device in the while loop
        while (flag){
            if (tempo>1000){
                flag=false;
                System.out.println("Tempo d'attente de la réponse du périphérique a expiré");
                tempo = 0;
            }
            else{
                flag = (port.getLastReceivedData()!=null && !port.getLastReceivedData().equals(RATTACHEMENT_AUTORISEE_PERIPHERIQUE));
                if (!flag){
                    System.out.println("|RATTACHEMENT_AUTORISEE_PERIPHERIQUE| recu de la part du périphérique");
                }
                tempo = tempo + 100;
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {}
            }
        }

        // Wait 10 secondes
        tempo = 0;
        seconde = 1000;
        while (tempo<5*seconde){
            System.out.println("Tempo = " + tempo);
            tempo = tempo + seconde;
            try {
                Thread.sleep(seconde);
            } catch (InterruptedException ex) {}
        }
        
        // The expected answer is received by the SESAME 
        if (!flag){
            System.out.println("|RATTACHEMENT_AUTORISEE_PERIPHERIQUE| recu de la part du periphérique");
            flag = true;
            tempo = 0;
            // Arrange the owner information and Send it
            String [] data_link = arrangeLinkingData();
            try {
                port.sendData(data_link);
            } catch (InterruptedException ex) {}
        }

        while (flag){
            if (tempo>7000){
                flag=false;
                System.out.println("Tempo d'attente de la réponse du périphérique a expiré");
                tempo = 0;
            }
            else{
                flag = (port.getLastReceivedData()!=null && !port.getLastReceivedData().equals(SESAME_RATTACHE_CORRECTEMENT));
                if (!flag){
                    System.out.println("|SESAME_RATTACHE_CORRECTEMENT| recu de la part du périphérique");
                    status_linking_sesame = true;
                }
                tempo = tempo + 100;
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {}
            }
        }
        
        // Wait 10 secondes
        tempo = 0;
        seconde = 1000;
        while (tempo<5*seconde){
            System.out.println("Tempo end = " + tempo);
            tempo = tempo + seconde;
            try {
                Thread.sleep(seconde);
            } catch (InterruptedException ex) {}
        }
        
        if (status_linking_owner && status_linking_sesame){
            System.out.println("L'enregistrement et le Rattachement du Sesame se sont effectués avec succés");
            // SEND "BONJOUR" and wait the answer of the device. The expected answer is "BONJOUR"  
            try {
                port.sendData(DEMANDE_CONFIRMATION_RATTACHEMENT);                
            }catch(InterruptedException e){
                System.out.println("Impossible to the send the following message : BONJOUR");
            }
        }
        else{
            System.out.println("L'enregistrement et le Rattachement du Sesame ne sont pas effectués correctement");   
        }
        
        lancer_procedure.setEnabled(true);
        corriger_info.setEnabled(true);
    }//GEN-LAST:event_lancer_procedureMouseReleased

    private void corriger_infoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corriger_infoMouseReleased
        // TODO add your handling code here:
        close();
        PeripheriqueIdentification periph_identification = new PeripheriqueIdentification();
        periph_identification.setUserChoice(periph.getTypeBien(), periph.getTypeAppartenance(), 
                                            periph.getEmplacement(), periph.getTypePorte(), periph.getCommentaire(),
                                            periph.getNumeroRue(), periph.getNomRue(), periph.getCodePostale(), periph.getVille(), periph.getPays());
        periph_identification.setVisible(true);
    }//GEN-LAST:event_corriger_infoMouseReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeripheriqueSummaryInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeripheriqueSummaryInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeripheriqueSummaryInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeripheriqueSummaryInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PeripheriqueSummaryInformation().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel code_postale_ville_jlabel;
    private javax.swing.JTextField commentaire_jTextField;
    private javax.swing.JToggleButton corriger_info;
    private javax.swing.JLabel emplacement_jlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton lancer_procedure;
    private javax.swing.JLabel numero_nom_voie_jlabel;
    private javax.swing.JLabel pays_jlabel;
    private javax.swing.JLabel type_appartenance_jlabel;
    private javax.swing.JLabel type_bien_jlabel;
    private javax.swing.JLabel type_porte_jlabel;
    // End of variables declaration//GEN-END:variables

    private static final long serialVersionUID = 42L;
    
    /*
     * Methode : close() allow you to close the current windows
     */
    private void close(){
        // Close the uart port before closing the windows
        port.closeUartPort();
        
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
    
    /**
     * Methode arrangeOwnerInformationForLinking() allows you to classify all the information 
     * about the owner of the SESAME. 
     * @return data[] which type is String
     */ 
    public String [] arrangeOwnerInformationForLinking (){
        String [] owner_data = null;
        String [] data = null;
        boolean flag_extraction = false;

        /* Deserializable of the file containing the information of the owner
         * to add the indentifier number and password 
         */          
        OwnerInformation owner = null;
        File file = new File("owner_information.ser");
        try (FileInputStream fileIn = new FileInputStream(file); ObjectInputStream in = new ObjectInputStream(fileIn)) {
            owner = (OwnerInformation) in.readObject();
            //System.out.println("Extraction de OwnerInformation");
            
            owner_data = owner.getOwnerInformationForLinking();
            flag_extraction = true;
            
        }catch(IOException io){
            System.out.println("Exception de IO : " + io.getMessage());
            flag_extraction = false;
        }catch(ClassNotFoundException c){
           System.err.println("OwnerInformation class not found : " + c.getMessage());
           flag_extraction = false;
        }
        
        if (flag_extraction){
            int size_data_owner = owner_data.length;
            data = new String[size_data_owner + 3];
            
            // Send the first frame to inform the device all the data received after taht frame is to save
            data[0]  = DEBUT_ENVOIE_INFORMATION_PROPRIETAIRE;

            // Put the linking information 
            System.arraycopy(owner_data, 0, data, 1, size_data_owner);
            /*for (int i=0; i<owner_data.length; i++){
                data[i+1] = owner_data[i];
            }*/

            // Create the checksum
            int formule = 0; 
            int number_element = owner_data.length;
            for (int j=0; j<number_element; j++){
                formule = formule + (number_element-j)*owner_data[j].length();
            }
            int checksum = formule - number_element*128;
            data[number_element + 1] = Integer.toString(checksum);

            // Send the last frame to inform the device that is the last data
            data[number_element + 2] = FIN_ENVOI_INFORMATION_PROPRIETAIRE;
        }
        else{
            data = new String[1];
            data[0] = "NOK";
        }
        System.out.println("Data : " + data);
        
        return data;
    }

    /**
     * Methode arrangeLinkingData() allows you to classify all the information 
     * about the connection between the SESAME and Device. 
     * @return data[] which type is String
     */ 
    public String [] arrangeLinkingData (){
        String [] linking_data = new String[10];
        String [] data = new String[13];

        linking_data[0] = periph.getTypeBien();
        linking_data[1] = periph.getTypeAppartenance();
        linking_data[2] = periph.getEmplacement();
        linking_data[3] = periph.getTypePorte();
        linking_data[4] = periph.getCommentaire();
        linking_data[5] = Integer.toString(periph.getNumeroRue());
        linking_data[6] = periph.getNomRue();
        linking_data[7] = Integer.toString(periph.getCodePostale());
        linking_data[8] = periph.getVille();
        linking_data[9] = periph.getPays(); 

        // Create the DeviceLinkingData
        DeviceLinkingData device = new DeviceLinkingData(linking_data);
        // Make the Serizlization
        File file = new File("linking_data.ser");
        try{
            try (FileOutputStream fileOut = new FileOutputStream(file); ObjectOutputStream out = new ObjectOutputStream(fileOut)) {
                out.writeObject(device);
                System.out.println("linking_data.ser file is created correcly");
            }
        }catch(IOException i)
        {
            System.out.println("Exception " + i.getMessage());
        }
        System.out.println("Object Device is created");
        // Send the first frame to inform the device that the Sesame is ready the send all the data about the linking
        data[0] = DEBUT_ENVOI_INFORMATION_RATTACHEMENT;
        
        // Put the linking information 
        for (int i=0; i<linking_data.length; i++){
            data[i+1] = linking_data[i];
        }
        System.out.println("the buffer of the linking data is Filled out correctly");
        //System.arraycopy(linking_data, 0, data, 1, linking_data.length);

        // Create the checksum
        int formule = 0; 
        int number_element = linking_data.length;
        for (int j=0; j<number_element; j++){
            formule = formule + (number_element-j)*linking_data[j].length();
        }
        int checksum = formule - number_element*128;
        data[number_element + 1] = Integer.toString(checksum);

        // Put the last frame to inform the device that is the last data about the linking
        data[number_element + 2] = FIN_ENVOI_INFORMATION_RATTACHEMENT;

        return data;
    }
}