/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SharingGUI;

import AccesGUI.*;
import HomeGUI.*;
import LinkingGUI.*;
import SesameApp.*;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.*;
import javax.swing.event.*;

/**
 *
 * @author LamineBA
 */
public class DeviceAvailableForSharing extends JFrame implements ListSelectionListener {

    /**
     * Creates new form ManageAcces
     */
    private String selected_item="";
    
    public DeviceAvailableForSharing() {
        initComponents();
        
        // init the list
        fillOutTheChoiceList();
        choisir_jbutton.setEnabled(false);
        annuler_jbutton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_titre = new javax.swing.JPanel();
        titre_fenetre = new javax.swing.JLabel();
        separator_jpanel = new javax.swing.JPanel();
        annuler_jbutton = new javax.swing.JButton();
        choisir_jbutton = new javax.swing.JButton();
        liste_peripherique = new java.awt.List();
        separator_jpanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Péripheriques administrateurs");

        titre_fenetre.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        titre_fenetre.setText("Liste des péripheriques administrateurs");

        javax.swing.GroupLayout jpanel_titreLayout = new javax.swing.GroupLayout(jpanel_titre);
        jpanel_titre.setLayout(jpanel_titreLayout);
        jpanel_titreLayout.setHorizontalGroup(
            jpanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_titreLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titre_fenetre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        jpanel_titreLayout.setVerticalGroup(
            jpanel_titreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_titreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre_fenetre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        separator_jpanel.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout separator_jpanelLayout = new javax.swing.GroupLayout(separator_jpanel);
        separator_jpanel.setLayout(separator_jpanelLayout);
        separator_jpanelLayout.setHorizontalGroup(
            separator_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separator_jpanelLayout.setVerticalGroup(
            separator_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        annuler_jbutton.setBackground(new java.awt.Color(255, 153, 153));
        annuler_jbutton.setText("Annuler");
        annuler_jbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                annuler_jbuttonMouseReleased(evt);
            }
        });

        choisir_jbutton.setBackground(new java.awt.Color(153, 255, 51));
        choisir_jbutton.setText("Choisir");
        choisir_jbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                choisir_jbuttonMouseReleased(evt);
            }
        });
        choisir_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choisir_jbuttonActionPerformed(evt);
            }
        });

        liste_peripherique.setBackground(new java.awt.Color(153, 153, 255));
        liste_peripherique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liste_peripheriqueMouseClicked(evt);
                listeAccrediteeMouseClickedEvent(evt);
            }
        });

        separator_jpanel1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout separator_jpanel1Layout = new javax.swing.GroupLayout(separator_jpanel1);
        separator_jpanel1.setLayout(separator_jpanel1Layout);
        separator_jpanel1Layout.setHorizontalGroup(
            separator_jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        separator_jpanel1Layout.setVerticalGroup(
            separator_jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpanel_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(separator_jpanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(separator_jpanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(liste_peripherique, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(annuler_jbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choisir_jbutton)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(liste_peripherique, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator_jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annuler_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choisir_jbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        //liste_peripherique.addListSelectionListener(this);

        setSize(new java.awt.Dimension(407, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void liste_peripheriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liste_peripheriqueMouseClicked
        // TODO add your handling code here:
        selected_item = liste_peripherique.getSelectedItem();
        System.out.println("Vous avez selectionné l'utilisateur : " + selected_item);
        choisir_jbutton.setEnabled(true);
    }//GEN-LAST:event_liste_peripheriqueMouseClicked

    private void choisir_jbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choisir_jbuttonMouseReleased
        // TODO add your handling code here:
        InfoAboutSelectedDevice selected_dev = new InfoAboutSelectedDevice ();
        selected_dev.setSelectedId(selected_item);
        selected_dev.update();
        selected_dev.setVisible(true);
    }//GEN-LAST:event_choisir_jbuttonMouseReleased

    private void annuler_jbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annuler_jbuttonMouseReleased
        // TODO add your handling code here:
        this.close();
    }//GEN-LAST:event_annuler_jbuttonMouseReleased

    private void listeAccrediteeMouseClickedEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeAccrediteeMouseClickedEvent
        // TODO add your handling code here:
    }//GEN-LAST:event_listeAccrediteeMouseClickedEvent

    private void choisir_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choisir_jbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choisir_jbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeviceAvailableForSharing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeviceAvailableForSharing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeviceAvailableForSharing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceAvailableForSharing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DeviceAvailableForSharing().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler_jbutton;
    private javax.swing.JButton choisir_jbutton;
    private javax.swing.JPanel jpanel_titre;
    private java.awt.List liste_peripherique;
    private javax.swing.JPanel separator_jpanel;
    private javax.swing.JPanel separator_jpanel1;
    private javax.swing.JLabel titre_fenetre;
    // End of variables declaration//GEN-END:variables
    private String [] device_list = {"DEVICE 01", "DEVICE 02", "DEVICE XYZ", "DEVICE ACD",
                                     "SESAME DOORS", "SESAME", "EveryGates", "Vitry sur Seine", "Paris", "France"};
    ListSelectionListener ecouteur = null;    
    /**
     * Methode : fillOutTheChoiceList() allows you to fill out the choice list for the user
     * This methode will search all the device linked with this SESAME. 
     */
    public void fillOutTheChoiceList(){
        System.out.println("<--- BEGIN : fillOutTheChoiceList() --->");
        
        String [] all_device_id;
        
        // Make the deserialization of the table file which is the database of the device
        IdentifiantAndKeyTable table_id_key = null;
        boolean flag_extraction =  false;
        File file = new File("identifiant_and_key_table.ser");
        try (FileInputStream fileIn = new FileInputStream(file); ObjectInputStream in = new ObjectInputStream(fileIn)) {
            table_id_key = (IdentifiantAndKeyTable) in.readObject();

            flag_extraction = true;

        }catch(IOException i){
            flag_extraction = false;
            System.out.println("IOException : " + i.getMessage());
        }catch(ClassNotFoundException c){
           System.out.println("DeviceLinkingData class not found");
           flag_extraction =false;
        }
        
        // Check if the deserialization is done succesffully
        if (flag_extraction){
            all_device_id = table_id_key.getAllLinkedDeviceId();
            if (all_device_id.length>0){
                // Fit the device array list 
                for (int i=0; i<all_device_id.length; i++){
                    liste_peripherique.add(all_device_id[i], i);
                }
            }
            else{
                for (int i=0; i<device_list.length; i++){
                    liste_peripherique.add(device_list[i], i);
                }
            }
        }
        else{
            for (int i=0; i<device_list.length; i++){
                liste_peripherique.add(device_list[i], i);
            }
        }
        System.out.println("<--- END : fillOutTheChoiceList() --->");
    }

    
    /**
     * Methode : close() allow you to close the current windows
     */
    private void close(){
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}