/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SharingGUI;

import SharingClass.*;
import AccesGUI.*;
import HomeGUI.*;
import LinkingGUI.*;
import SesameApp.*;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LamineBA
 */
public class IdentifyTheReceiver extends javax.swing.JFrame implements java.io.Serializable{
    private String id_sesame_guest;
    private String s_pseudo;
    private String s_raison;
    private String s_relation;
    private Date date_debut;
    private Date date_fin;
    private Date date_du_jour = null; // your date
        
    /**
     * Creates new form ThirdWindows
     */
    public IdentifyTheReceiver() {
        initComponents();
        this.listerRelation();
        date_du_jour = new Date(); // your date
        Calendar cal = Calendar.getInstance();
        cal.setTime(date_du_jour);
        LocalDate localDate = date_du_jour.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int year  = localDate.getYear()-1900;
        int month = localDate.getMonthValue()-1;
        int day   = localDate.getDayOfMonth();
        date_du_jour.setDate(day);
        date_du_jour.setMonth(month);
        date_du_jour.setYear(year);
        System.out.println("Date = " + date_du_jour);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decliner_jbutton = new javax.swing.JToggleButton();
        accepter_jbutton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pseudo_jformattedtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date_debut_partage = new org.jdesktop.swingx.JXDatePicker();
        date_fin_partage = new org.jdesktop.swingx.JXDatePicker();
        raison_partage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        relation_choice = new java.awt.Choice();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        continuer_jbutton = new javax.swing.JToggleButton();
        precedent_jbutton = new javax.swing.JToggleButton();

        decliner_jbutton.setBackground(new java.awt.Color(255, 0, 0));
        decliner_jbutton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        decliner_jbutton.setText("Decliner");
        decliner_jbutton.setSize(new java.awt.Dimension(140, 30));
        decliner_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decliner_jbuttonActionPerformed(evt);
            }
        });

        accepter_jbutton.setBackground(new java.awt.Color(0, 255, 51));
        accepter_jbutton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        accepter_jbutton.setText("Accepter");
        accepter_jbutton.setSize(new java.awt.Dimension(140, 30));
        accepter_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepter_jbuttonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enregistrement de l'accrédité");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Enregistrement des informations sur l'accrédité");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Pseudo attribué : ");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Date de début du partage : ");

        pseudo_jformattedtext.setBackground(new java.awt.Color(153, 153, 255));
        pseudo_jformattedtext.setFont(new java.awt.Font("Times", 0, 14)); // NOI18N
        pseudo_jformattedtext.setText("pseudo_test");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Date de fin    du partage : ");

        date_debut_partage.setBackground(new java.awt.Color(153, 153, 255));

        date_fin_partage.setBackground(new java.awt.Color(153, 153, 255));

        raison_partage.setBackground(new java.awt.Color(153, 153, 255));
        raison_partage.setFont(new java.awt.Font("Times", 0, 14)); // NOI18N
        raison_partage.setText("Il s'agit d'une partage de test");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("La raison du partage des accès");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Relation avec l'utilisateur : ");

        relation_choice.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raison_partage, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(102, 102, 102)
                            .addComponent(pseudo_jformattedtext))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date_debut_partage, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(32, 32, 32)
                            .addComponent(relation_choice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(39, 39, 39)
                            .addComponent(date_fin_partage, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pseudo_jformattedtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raison_partage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(relation_choice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(date_debut_partage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(date_fin_partage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        continuer_jbutton.setBackground(new java.awt.Color(204, 255, 204));
        continuer_jbutton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        continuer_jbutton.setText("Continuer");
        continuer_jbutton.setSize(new java.awt.Dimension(140, 30));
        continuer_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuer_jbuttonActionPerformed(evt);
            }
        });

        precedent_jbutton.setBackground(new java.awt.Color(255, 153, 153));
        precedent_jbutton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        precedent_jbutton.setText("Précédent");
        precedent_jbutton.setSize(new java.awt.Dimension(140, 30));
        precedent_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedent_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(precedent_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continuer_jbutton)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(continuer_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(precedent_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(435, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void decliner_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decliner_jbuttonActionPerformed
        //close();
        
    }//GEN-LAST:event_decliner_jbuttonActionPerformed

    private void accepter_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepter_jbuttonActionPerformed
        //close();
    }//GEN-LAST:event_accepter_jbuttonActionPerformed

    private void precedent_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedent_jbuttonActionPerformed
        close();
    }//GEN-LAST:event_precedent_jbuttonActionPerformed

    private void continuer_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuer_jbuttonActionPerformed
    
        // Lire d'abord les données saisies par l'utilisateur
        readData();
        if (isDataTypedValide()){
            if (isTypedDataCorrect()){
                System.out.println("Correct");
                // Arrange the data about the guest sharing 
                String [] guest_data = new String[10];
                guest_data[0] = id_sesame_guest;
                guest_data[1] = s_pseudo;
                guest_data[2] = s_raison;
                guest_data[3] = s_relation;
                
                // Date which the shared will begin
                guest_data[4] = Integer.toString(date_debut.getDate());
                guest_data[5] = Integer.toString(date_debut.getMonth());
                guest_data[6] = Integer.toString(date_debut.getYear());
                
                // Date which the shared will end
                guest_data[7] = Integer.toString(date_fin.getDate());
                guest_data[8] = Integer.toString(date_fin.getMonth());
                guest_data[9] = Integer.toString(date_fin.getYear());
                
                // Create the class "GuestSharingData"
                GuestSharingData guest = new GuestSharingData(guest_data);
                System.out.println(guest);
                
                // Make the serialization
                File file = new File("guest_sharing_information.ser");
                // Make the serialization to save the owner information on a txt file
                try
                {
                    try (FileOutputStream fileOut = new FileOutputStream(file); ObjectOutputStream out = new ObjectOutputStream(fileOut)) {
                        out.writeObject(guest);
                    }
                   System.out.println("Serialized data is saved in owner_information.ser");
                }catch(IOException i){}
                
                close();
            }
            else{
                System.out.println("Incorrect");
            }
        }
        else{
            //CheckDataTyped();
            System.out.println("Verifier les données saisies");
        }
        
    }//GEN-LAST:event_continuer_jbuttonActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdentifyTheReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdentifyTheReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdentifyTheReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdentifyTheReceiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IdentifyTheReceiver().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton accepter_jbutton;
    private javax.swing.JToggleButton continuer_jbutton;
    private org.jdesktop.swingx.JXDatePicker date_debut_partage;
    private org.jdesktop.swingx.JXDatePicker date_fin_partage;
    private javax.swing.JToggleButton decliner_jbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton precedent_jbutton;
    private javax.swing.JTextField pseudo_jformattedtext;
    private javax.swing.JTextField raison_partage;
    private java.awt.Choice relation_choice;
    // End of variables declaration//GEN-END:variables

    /*
     * Cette méthode permet de lire les informations saisies par l'utilisateur après 
     * avoir validé la requête. 
     */
    private void readData(){
        
        s_pseudo = pseudo_jformattedtext.getText();
        s_raison = raison_partage.getText();
        s_relation = relation_choice.getSelectedItem();
        
        // Récuperation des dates de début et de fin
        try {
                date_debut = date_debut_partage.getDate(); 
                date_fin   = date_fin_partage.getDate();
                
                date_debut.setYear(date_debut.getYear()+1900);
                date_fin.setYear(date_fin.getYear()+1900);
        }
        catch (Exception e){
                System.err.println("La date de naissance saisie est incorrecte");
        }
    }
    
    private boolean isChoosenDateCorrect (){
        boolean first_flag = (date_debut instanceof Date) && (date_fin instanceof Date);
        boolean second_flag = false;
        
        int day_start=0;
        int month_start = 0;
        int year_start=0;
        
        int day_end=0;
        int month_end=0;
        int year_end=0;
        
        try{
            day_start = date_debut.getDay();
            month_start = date_debut.getMonth();
            year_start = date_debut.getYear();
        }catch(Exception ex){
            System.out.println("La date de début saisie est incorrect");
            day_start=0;
            month_start = 0;
            year_start=0;
            date_debut = new Date();
            date_debut.setDate(day_start);
            date_debut.setMonth(month_start);
            date_debut.setYear(year_start);
        }
        
        try{
            day_end = date_fin.getDay();
            month_end = date_fin.getMonth();
            year_end = date_fin.getYear();
        }catch(Exception ex){
            System.out.println("La date de fin saisie est incorrect");
            day_end=0;
            month_end=0;
            year_end=0;
            date_fin = new Date();
            date_fin.setDate(day_end);
            date_fin.setMonth(month_end);
            date_fin.setYear(year_end);
        }
        
        //System.out.println("Comparaison date de début et date du jour : " + date_debut.equals(date_du_jour));
        if (date_fin.after(date_debut))
            second_flag = true;
            
        System.out.println("Flag checkDateChoosen() first flag = " + first_flag);
        System.out.println("Flag checkDateChoosen() second flag = " + second_flag);
        
        return first_flag && second_flag;
    }
    /*
     * Cette méthode permet de vérifier si les données saisies sont correctes ou pas.
     */
    private boolean isDataTypedValide (){
        boolean first_flag = (s_pseudo   != null && !s_pseudo.isEmpty()) && 
                             (s_raison   != null && !s_raison.isEmpty()) && 
                             (s_relation != null && !s_relation.isEmpty() && !s_relation.equals("..."));
        
        boolean second_flag = isChoosenDateCorrect();
        
        System.out.println("Flag isDataTypedValide() first flag = " + first_flag);
        System.out.println("Flag isDataTypedValide() second flag = " + second_flag);
        
        return first_flag && second_flag;
    }
    
    /*
     * Cette méthode permet de verifier les données saisies
     * incorrectes et notifie l'utilisateur le champ à vérifier.
     */
    private boolean isTypedDataCorrect (){
        boolean first_flag = false;
        boolean second_flag = false;
        int test_count = 0;

        String notification = "";

        if (s_pseudo == null || s_pseudo.isEmpty()){
            notification += " - Pseudo\n";
        }
        else{
            test_count += 1;
        }

        if (s_raison == null || s_raison.isEmpty()){
            notification += " - La raison du partage\n";
        }
        else{
            test_count += 1;
        }

        if (s_relation == null || s_relation.equals("...")){
            notification += " - La relation avec le destinataire\n";
        }
        else{
            test_count += 1;
        }
        System.out.println("Notif = " + notification);
        second_flag = isChoosenDateCorrect();
        
        System.out.println("test_count = " + test_count);
        first_flag = test_count==3;
            
        System.out.println("Flag isTypedDataCorrect() first flag = " + first_flag);
        System.out.println("Flag isTypedDataCorrect() second flag = " + second_flag);
        
        return first_flag && second_flag;
    }
    
    private void close(){
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
    
    /**
     * Methode listerRelation : Liste les types de relation défini. 
     * cette liste est à remettre à jour plus tard. 
     * 
     */
    private void listerRelation (){
      
        relation_choice.add("...");
        relation_choice.add("Epoux");
        relation_choice.add("Enfant");
        relation_choice.add("Frere");
        relation_choice.add("Soeur");
        relation_choice.add("Pere");
        relation_choice.add("Mere");
        relation_choice.add("Ami");
        relation_choice.add("Collaborateur");
        relation_choice.add("Livreur");
        relation_choice.add("Autre");
    }
    
    public void setGuestId(String guest_id){
         id_sesame_guest = guest_id;
    }
    private static final long serialVersionUID = 42L; 
}
